---
title: "Epiverse-TRACE ggplot2 theme and scale demo"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Epiverse-TRACE ggplot2 theme and scale demo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
devtools::load_all()#library(tracetheme)
library(ggplot2)
library(outbreaks)
library(incidence2)
library(linelist)
```

The examples below are taken from [ggplot2 documentation](https://ggplot2.tidyverse.org/) and are intended to demonstrate the effect of the `theme_trace()` and `scale_trace()` functions.

## Line graphs/time series

```{r}
df <- incidence2::incidence(outbreaks::ebola_sim_clean$linelist, date_index = "date_of_onset", interval = 7)
ggplot(df, aes(date_index, count)) +
  geom_line() + 
  labs(x = "Date", y = "Confirmed cases") +
  theme_trace()
```

## Scatter plots

```{r}
ggplot(df, aes(date_index, count)) +
  geom_point() +
  labs(x = "Date", y = "Confirmed cases") +
  theme_trace()
```

## Bar / column charts

```{r}
isoweek_df <- base::transform(outbreaks::ebola_sim_clean$linelist, date_of_onset = as_isoweek(date_of_onset)) 
ggplot(isoweek_df, aes(date_of_onset)) +
  geom_bar() +
  labs(x = "Date", y = "Confirmed cases") +
  theme_trace()
```



```{r}
library(maps)
crimes <- data.frame(state = tolower(rownames(USArrests)), USArrests)

# Equivalent to crimes %>% tidyr::pivot_longer(Murder:Rape)
vars <- lapply(names(crimes)[-1], function(j) {
  data.frame(state = crimes$state, variable = j, value = crimes[[j]])
})
crimes_long <- do.call("rbind", vars)

states_map <- map_data("state")

ggplot(crimes_long, aes(map_id = state)) +
  geom_map(aes(fill = value), map = states_map) +
  coord_sf(
    crs = 5070, default_crs = 4326,
    xlim = c(-125, -70), ylim = c(25, 52)
  ) +
  facet_wrap(~variable) +
  theme_trace()
```

## Distribution plots (parametric and non-parametric) 

```{r}
ggplot() +
  geom_function(fun = dnorm) +
  xlim(-5, 5) +
  theme_trace()
```

## Densities

```{r}
ggplot(isoweek_df, aes(date_of_onset)) +
  geom_density() +
   labs(x = "Date", y = "Confirmed cases") +
  theme_trace()
```

## Heatmaps

```{r}
ggplot(faithful, aes(x = eruptions, y = waiting)) +
  geom_point() +
  geom_density_2d_filled(alpha = 0.5) +
  theme_trace()
```

```{r}
ggplot(diamonds, aes(x, y)) +
  geom_bin_2d() +
  theme_trace()
```

## Networks

This example is pulled from ggraph documentation

```{r}
library(ggraph)
library(tidygraph)

set_graph_style(plot_margin = margin(1, 1, 1, 1))
graph <- as_tbl_graph(highschool)

# Not specifying the layout - defaults to "auto"
ggraph(graph) +
  geom_edge_link(aes(colour = factor(year))) +
  geom_node_point()
```

## Concept maps / flowcharts
